# Generated by Django 4.2.20 on 2025-03-31 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("repository", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("deployment_frequency", "Deployment Frequency"),
                            ("change_delivery_time", "Change Delivery Time"),
                            ("service_recovery_time", "Service Recovery Time"),
                            ("change_failure_rate", "Change Failure Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metrics.project",
                    ),
                ),
            ],
        ),
    ]
