# Generated by Django 4.2.20 on 2025-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_metric_variance"),
    ]

    operations = [
        migrations.RemoveField(model_name="metric", name="date_recorded",),
        migrations.AddField(
            model_name="metric", name="since", field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="metric", name="until", field=models.DateTimeField(null=True),
        ),
    ]
