# Generated by Django 4.2.20 on 2025-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_remove_metric_date_recorded_metric_since_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("release_frequency", "Release Frequency"),
                    (
                        "lead_time_for_released_changes",
                        "Lead Time for Released Changes",
                    ),
                    ("time_to_repair_code", "Time to Repair Code"),
                    ("bug_issues_rate", "Bug Issues Rate"),
                ],
                max_length=50,
            ),
        ),
    ]
