services:
     - type: web
       name: dora-app
       env: python
       buildCommand: "./build.sh"
       startCommand: "./startup.sh"
       envVars:
         - key: DATABASE_URL
           fromDatabase:
             name: dora-db
             property: connectionString
         - key: SECRET_KEY
           generateValue: true
         - key: DEBUG
           value: False
         - key: ALLOWED_HOSTS
           value: localhost,127.0.0.1,.onrender.com
         - key: CORS_ALLOWED_ORIGINS
           value: http://localhost:3000,https://dora-21tx.onrender.com
         - key: CSRF_TRUSTED_ORIGINS
           value: http://localhost:3000,https://dora-21tx.onrender.com
         - key: GITHUB_USERNAME
           value: mohamedabouri
         - key: GITHUB_PASSWORD
           sync: false
         - key: GITHUB_OWNER
           value: grafana
         - key: GITHUB_REPOSITORY
           value: grafana
         - key: SINCE_DAY
           value: 2022-07-01T00:00:00+00:00
         - key: UNTIL_DAY
           value: 2022-12-31T23:59:59+00:00
         - key: BUG_LABEL
           value: type/bug
         - key: DB_USER
           value: dora_us3r
         - key: DB_PASSWORD
           value: dora_p4ssw0rd
         - key: DB_HOST
           value: localhost
         - key: DB_PORT
           value: 5432
         - key: DB_NAME
           value: dora

   databases:
     - name: dora-db
       plan: free